src/server/Web/DataGate.Web/Controllers/Users/LayoutController.cs
// Copyright (c) DataGate Project. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace DataGate.Web.Controllers.Users
{
    using System.Threading.Tasks;

    using DataGate.Common;
    using DataGate.Data.Common.Repositories.UsersContext;
    using DataGate.Data.Models.Columns;
    using DataGate.Services.Data.Layouts;
    using DataGate.Web.InputModels.Layouts;
    using DataGate.Web.Resources;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class LayoutController : BaseController
    {
        private readonly ILayoutService layoutService;
        private readonly IUserRepository<UserFundColumn> userFRepository;
        private readonly IUserRepository<UserSubFundColumn> userSFRepository;
        private readonly IUserRepository<UserShareClassColumn> userSCRepository;
        private readonly SharedLocalizationService sharedLocalizer;

        public LayoutController(
            ILayoutService layoutService,
            IUserRepository<UserFundColumn> userFRepository,
            IUserRepository<UserSubFundColumn> userSFRepository,
            IUserRepository<UserShareClassColumn> userSCRepository,
            SharedLocalizationService sharedLocalizer)
        {
            this.layoutService = layoutService;
            this.userFRepository = userFRepository;
            this.userSFRepository = userSFRepository;
            this.userSCRepository = userSCRepository;
            this.sharedLocalizer = sharedLocalizer;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Save(SaveLayoutInputModel input)
        {
            if (input.SelectedColumns != null)
            {
                await this.SaveLayout(input);

                return this.Json(new { success = true, controller = input.ControllerName, area = input.AreaOrigin });
            }

            return this.Json(new { success = false });
        }

        public IActionResult OnSaveLayoutSuccess(string controllerOrigin, string areaOrigin)
        {
            return this.ShowInfo(
                   this.sharedLocalizer.GetHtmlString(InfoMessages.LayoutSaved),
                   EndpointsConstants.ActionAll,
                   controllerOrigin,
                   new { area = areaOrigin });
        }

        public async Task<IActionResult> Default(string controllerName)
        {
            var area = await this.RestoreLayout(controllerName);

            return this.RedirectToAction(
                EndpointsConstants.ActionAll,
                controllerName,
                new { area = area });
        }

        private async Task<string> RestoreLayout(string controller)
        {
            string area = string.Empty;
            var user = await this.layoutService.UserWithLayouts(this.User);

            switch (controller)
            {
                case EndpointsConstants.FundsController:
                    area = EndpointsConstants.FundArea;
                    await this.userFRepository.RestoreLayout(user.UserFundColumns);
                    break;
                case EndpointsConstants.DisplaySub + EndpointsConstants.FundsController:
                    area = EndpointsConstants.DisplaySub + EndpointsConstants.FundArea;
                    await this.userSFRepository.RestoreLayout(user.UserSubFundColumns);
                    break;
                case EndpointsConstants.ShareClassesController:
                    area = EndpointsConstants.ShareClassArea;
                    await this.userSCRepository.RestoreLayout(user.UserShareClassColumns);
                    break;
            }

            return area;
        }

        private async Task SaveLayout(SaveLayoutInputModel input)
        {
            var user = await this.layoutService.UserWithLayouts(this.User);

            switch (input.ControllerName)
            {
                case EndpointsConstants.FundsController:
                    var columnsToDbF = this.layoutService.ColumnsToDb<UserFundColumn>(input.SelectedColumns, user.Id);
                    await this.userFRepository.SaveLayout(user.UserFundColumns, columnsToDbF);
                    break;
                case EndpointsConstants.DisplaySub + EndpointsConstants.FundsController:
                    var columnsToDbSF = this.layoutService.ColumnsToDb<UserSubFundColumn>(input.SelectedColumns, user.Id);
                    await this.userSFRepository.SaveLayout(user.UserSubFundColumns, columnsToDbSF);
                    break;
                case EndpointsConstants.ShareClassesController:
                    var columnsToDbSC = this.layoutService.ColumnsToDb<UserShareClassColumn>(input.SelectedColumns, user.Id);
                    await this.userSCRepository.SaveLayout(user.UserShareClassColumns, columnsToDbSC);
                    break;
            }
        }

    }
}

src/server/Web/DataGate.Web/Views/Shared/AllEntities/_TableLayout.cshtml
@model EntitiesViewModel

@{ 
    var numberPreSelectedColumns = GlobalConstants.PreSelectedColumnsCount;
    var controller = this.ViewContext.RouteData.Values[EndpointsConstants.ControllerRouteDataValue].ToString();
}

<div class="modal"
     id="columnModal"
     role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div>
                    <h2 class="text-center">
                        @SharedLocalizer.GetHtmlString("defineLayout")
                    </h2>
                    <select asp-for="PreSelectedColumns" style="width:60%" hidden>
                        @for (int col = 0; col < numberPreSelectedColumns; col++)
                        {
                            <option selected value="@Model.HeadersSelection[col]">
                                @Model.HeadersSelection[col]
                            </option>
                        }
                    </select>

                    <select class="multiselect" multiple="multiple" asp-for="SelectedColumns" style="width:60%">
                        @for (int col = numberPreSelectedColumns; col < Model.HeadersSelection.Count; col++)
                        {
                            <option value="@Model.HeadersSelection[col]">
                                @Model.HeadersSelection[col]
                            </option>
                        }
                    </select>
                    <br />
                </div>
            </div>
            <div class="modal-footer">
                <div class="modal-footer-save-btn-container">
                    <a id="btn-save-layout"
                       class="btn btn-datagate btn-sm mr-2">
                        @SharedLocalizer.GetHtmlString("Save")
                    </a>

                    <a asp-area=""
                       asp-controller="Layout"
                       asp-action="Default"
                       asp-route-controllerName="@controller"
                       
                       id="btn-default-layout"
                       class="btn btn-datagate btn-sm ml-2">
                        @SharedLocalizer.GetHtmlString("Default")
                    </a>

                </div>

                <div>
                    <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">
                        @SharedLocalizer.GetHtmlString("Close")
                    </button>

                    <input type="submit"
                           name="Command"
                           value=@SharedLocalizer.GetHtmlString("Apply")
                           class="btn btn-datagate ml-2" />
                </div>
            </div>
        </div>
    </div>
</div>

src/server/Web/DataGate.Web/Views/Shared/AllEntities/_Toolbar.cshtml
@model EntitiesViewModel

@{
    var controller = this.ViewContext
        .RouteData
        .Values[EndpointsConstants.ControllerRouteDataValue]
        .ToString();
    var routeCreate = StringSwapper.ByController(controller,
                                                 EndpointsConstants.RouteCreate + EndpointsConstants.FundArea,
                                                 EndpointsConstants.RouteCreate + EndpointsConstants.DisplaySub + EndpointsConstants.FundArea,
                                                 EndpointsConstants.RouteCreate + EndpointsConstants.ShareClassArea);
}

<form class="d-flex"
      method="post"
      asp-action="All"
      id="update-form">

    <div>
        <label>@SharedLocalizer.GetHtmlString("As of:")</label>
        <input type="date"
               asp-for="Date"
               min="2018-01-01"
               required>
        <input type="submit"
               class="btn btn-datagate btn-sm mb-1"
               name="Command"
               value="@SharedLocalizer.GetHtmlString("Update")"></>
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="vertical mx-3"></div>

    <div>
        <button type="button"
                class="btn btn-sm btn-datagate"
                data-toggle="modal"
                data-target="#columnModal"
                name="showColumnSelection">
            @SharedLocalizer.GetHtmlString("Layout")
        </button>
    </div>

    <div class="switch-datagate-div ml-4">
        <label class="switch-datagate switch-datagate-sm mt-1">
            <input type="checkbox"
                   asp-for="IsActive"
                   id="activeCheckBox">
            <span class="switch-datagate-style"></span>
            <span class="d-block text-switch-datagate">@SharedLocalizer.GetHtmlString("Active")</span>

        </label>
    </div>

    <partial name="AllEntities/_TableLayout" />
</form>

<div class="vertical mx-3"></div>

<div>
    <form method="post" id="extract-form"></form>

    <button class="btn btn-sm btn-datagate"
            id="btn-extract-excel"
            type="button"
            value="Excel">
        EXCEL
    </button>

    <button class="btn btn-sm btn-datagate ml-4"
            id="btn-extract-pdf"
            type="button"
            value="PDF">
        PDF
    </button>
</div>

<div class="vertical mx-3"></div>

@if (this.User.IsInRole(GlobalConstants.AdministratorRoleName) || this.User.IsInRole(GlobalConstants.LegalRoleName))
{
    <div>
        <a asp-area="Admin"
           asp-route="@routeCreate"
           class="btn btn-sm btn-datagate">
            @SharedLocalizer.GetHtmlString("Create")
        </a>
    </div>
}

src/server/Web/DataGate.Web/Views/Shared/AllEntities/_ViewTable.cshtml
@model EntitiesViewModel

@{
    var controller = this.ViewContext
        .RouteData
        .Values[EndpointsConstants.ControllerRouteDataValue]
        .ToString();
    var routeDetails = StringSwapper.ByController(controller,
                                                  EndpointsConstants.RouteDetails + EndpointsConstants.FundArea,
                                                  EndpointsConstants.RouteDetails + EndpointsConstants.DisplaySub + EndpointsConstants.FundArea,
                                                  EndpointsConstants.RouteDetails + EndpointsConstants.ShareClassArea);

    var entityAbr = StringSwapper.ByController(controller,
                                            EndpointsConstants.FundAbbreviation,
                                            EndpointsConstants.SubFundAbbreviation,
                                            EndpointsConstants.ShareClassAbbreviation);

    var entityId = string.Empty;
}

<div class="table-responsive border-0 mx-auto">
    <table class="table table-hover table-view-datagate" id="table-to-extract" hidden>
        <thead>
            <tr>
                @for (int header = 0; header < Model.Headers.Count; header++)
                {
                    if (Model.Headers[header] == "NAME")
                    {
                        <th class="th-name" data-toggle="tooltip"
                            data-placement="top"
                            title="@Model.Headers[header]">
                            @Model.Headers[header]
                        </th>
                    }
                    else
                    {
                        <th data-toggle="tooltip"
                            data-placement="top"
                            title="@Model.Headers[header]">
                            @Model.Headers[header]
                        </th>
                    }
                }
            </tr>
        </thead>
        <tbody id="tbody-update-inactive">
            @foreach (var row in Model.Values)
            {
                entityId = row[GlobalConstants.IndexEntityIdInTable];

                <tr>
                    @for (int col = 0; col < row.Length; col++)
                    {
                        if (Model.Headers.ToList()[col] == "NAME")
                        {
                            <td class="td-name-link">
                                <a asp-route="@routeDetails" asp-route-id="@entityId" asp-route-date="@Model.Date">
                                    @row[col]
                                </a>
                            </td>
                        }
                        else if (Model.Headers.ToList()[col] == "ID")
                        {
                            <td class="">
                                @row[col]_@entityAbr.ToUpper()
                            </td>
                        }
                        else
                        {
                            <td class="">
                                @row[col]
                            </td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>
</div>